version: '3.9'
services:
  klipper:
    image: mkuf/klipper:latest
    container_name: klipper_Ender5
    privileged: true
    volumes:
      - /dev:/dev
      - ./printer.cfg:/opt/printer_data/config/printer.cfg
      - ./run:/opt/printer_data/run
      - ./gcode:/opt/printer_data/gcodes
      - ./logs:/opt/printer_data/logs

  moonraker:
    image: mkuf/moonraker:latest
    container_name: moonraker_Ender5
    ports:
      - "7125:7125"
    volumes:
      - ./moonraker.conf:/opt/printer_data/config/moonraker.conf
      - ./run:/opt/printer_data/run
      - ./gcode:/opt/printer_data/gcodes
      - ./logs:/opt/printer_data/logs
    networks:
      default:
        ipv4_address: 10.244.104.52

networks:
  network1:
    name: 3dp_outerNetwork
    external: true